// <auto-generated />
using System;
using ASP.NETCOREWEBAPICRUD.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NETCOREWEBAPICRUD.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    partial class UsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ASP.NETCOREWEBAPICRUD.Context.Categories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Work"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Home"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Leisure"
                        });
                });

            modelBuilder.Entity("ASP.NETCOREWEBAPICRUD.Context.Taskss", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TaskId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            CategoryId = 1,
                            Description = "This is a seed task",
                            DueDate = new DateTime(2024, 8, 2, 11, 12, 11, 782, DateTimeKind.Local).AddTicks(2974),
                            IsCompleted = false,
                            Name = "John",
                            Priority = 1,
                            Title = "Initial Task 1"
                        },
                        new
                        {
                            TaskId = 2,
                            CategoryId = 2,
                            Description = "This is another seed task",
                            DueDate = new DateTime(2024, 8, 5, 11, 12, 11, 782, DateTimeKind.Local).AddTicks(3004),
                            IsCompleted = false,
                            Name = "Chris",
                            Priority = 2,
                            Title = "Initial Task 2"
                        });
                });

            modelBuilder.Entity("ASP.NETCOREWEBAPICRUD.Context.Users", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Name = "John",
                            Address = "New York",
                            Designation = "Developer",
                            Email = "2021cs661@student.uet.edu.pk",
                            Password = "XYZ1Inc"
                        },
                        new
                        {
                            Name = "Chris",
                            Address = "New York",
                            Designation = "Manager",
                            Email = "2021cs662@student.uet.edu.pk",
                            Password = "ABC2Inc"
                        },
                        new
                        {
                            Name = "Mukesh",
                            Address = "New Delhi",
                            Designation = "Consultant",
                            Email = "2021cs663@student.uet.edu.pk",
                            Password = "XYZ3Inc"
                        });
                });

            modelBuilder.Entity("ASP.NETCOREWEBAPICRUD.Context.Taskss", b =>
                {
                    b.HasOne("ASP.NETCOREWEBAPICRUD.Context.Categories", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP.NETCOREWEBAPICRUD.Context.Users", "User")
                        .WithMany()
                        .HasForeignKey("Name")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
